# Generated by Django 4.2.6 on 2023-10-24 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='lessonviewinfo',
            unique_together={('lesson',)},
        ),
    ]
